version: 2.1

jobs:
  test-api:
    docker:
      - image: cimg/node:20.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Run Vitest Tests
          command: npm run test

  build-and-deploy:
    docker:
      - image: cimg/node:20.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Deploy
          command: |
            echo "Executando deploy do código compilado..."
            echo "Arquivos prontos para deploy no workspace:"
            ls -R dist/

workflows:
  api-workflow:
    jobs:
      - test-api
      - build-and-deploy:
          requires:
            - test-api
          filters:
            branches:
              only:
                - main